excluded:
  - build
  - specs
  - .specify
  - ai
  - .github
  - README.md
  - WARP.md

disabled_rules:
  - todo
  - type_name
  - nesting
  - cyclomatic_complexity
  - file_length
  - force_cast
  - multiple_closures_with_trailing_closure

line_length:
  warning: 160
  error: 200

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 350
  error: 400

trailing_whitespace:
  ignores_empty_lines: true

identifier_name:
  min_length: 2
  allowed_symbols: ["_"]
  excluded: ["id", "i", "j", "x", "y"]

reporter: "xcode"
